#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# rheaps documentation build configuration file.
#
# This file is execfile()d with the current directory set to its
# containing dir.

import os
import sys

from sphinx_gallery.sorting import ExplicitOrder

on_rtd = os.environ.get('READTHEDOCS') == 'True'

if not on_rtd:
    sys.path.insert(0, os.path.abspath('..'))

import rheaps

# -- General configuration ------------------------------------------------

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.mathjax',
    'sphinx.ext.todo',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx_gallery.gen_gallery',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = rheaps.__title__
copyright = rheaps.__copyright__
author = rheaps.__author__

# The version info for the project you're documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
version = rheaps.__version__
release = rheaps.__version__
# Version of the underlying `rheaps` Rust crate (https://docs.rs/rheaps)
# this build embeds.
backend_version = rheaps.__backend_version__

# Create some global substitutions
rst_prolog = """
.. |BackendVersion| replace:: {backend_version}
.. |Project| replace:: {project}
.. |Bindings| replace:: Python bindings of {project}
""".format(
    backend_version=backend_version,
    project=project
)

# The language for content autogenerated by Sphinx.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output ----------------------------------------------

if on_rtd:
    html_theme = 'default'
else:
    html_theme = 'sphinx_rtd_theme'

html_theme_options = {
    'canonical_url': '',
    'logo_only': False,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'style_nav_header_background': 'white',
    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory.
html_static_path = ['_static']

html_sidebars = {
    '**': [
        'relations.html',
        'searchbox.html',
    ]
}

# -- Options for HTMLHelp output ------------------------------------------

htmlhelp_basename = 'rheapsdoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    'papersize': 'a4paper',
    'pointsize': '11pt',
}

latex_documents = [
    (master_doc, 'rheaps.tex', 'rheaps Documentation',
     'Dimitrios Michail', 'manual'),
]

# -- Options for manual page output ---------------------------------------

man_pages = [
    (master_doc, 'rheaps', 'rheaps Documentation',
     [author], 1)
]

# -- Options for Texinfo output -------------------------------------------

texinfo_documents = [
    (master_doc, 'rheaps', 'rheaps Documentation',
     author, 'rheaps', 'Python bindings for the rheaps heap library.',
     'Miscellaneous'),
]

#
# Sphinx gallery configuration
#
sphinx_gallery_conf = {
    'examples_dirs': '../examples',   # path to your example scripts
    'subsection_order': ExplicitOrder(
        [
            '../examples/addressable',
            '../examples/array',
            '../examples/monotone',
        ]
    ),
    'gallery_dirs': 'auto_examples',  # path to where to save gallery generated output
    'download_all_examples': False,
}
